# Generated by Django 5.0.14 on 2025-06-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
